api_version = "2026-01"
[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
handle = "discount-order-exclude-block"
uid = "37c74f6f-6786-38b6-8494-5238be9c4c6b4ba91ba6"
type = "ui_extension"
# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"

[[extensions.metafields]]
namespace = "b-h-discounts"
key = "function-configuration"
